### ISSUE TITLE
rename Writer to Client

### ISSUE THREAD

**Issue by suyash** [performancecopilot/speed#15]
The fundamental reason for doing this is that the name writer in the golang community implies to most that the type implements io.Writer, and initially **it did**, but later on all the writing capability was abstracted away into bytebuffer, and the Buffer type does implement [io.Writer](https://github.com/performancecopilot/speed/blob/master/bytebuffer/buffer.go#L25), but speed.Writer doesn't, and I don't think the name is apt anymore. Looking at the current definition of the interface, I think Client is a more appropriate name, and will probably create less confusion.

**Comment by natoscott** [comment]
@suyash the suggested change certainly makes sense to me, go for it.
