### ISSUE TITLE
Expose Go runtime metrics

### ISSUE THREAD

**Issue by saurvs** [performancecopilot/speed#42]
The Go `runtime` package exposes metrics related to the host CPU, memory usage and garbage collector.

We can either add a new example demonstrating how to expose those metrics using the existing API, or we can implement a new `PCPInstanceMetric` called `GoRuntime`, which exposes those metrics and implements a `SetTimeResolution` method for periodically updating the metrics.

**Comment by suyash** [comment]
An example would be nice, there was also a stretch goal for last year (#7) to create a CLI application on top of the API that does that

**Comment by saurvs** [comment]
Ok. I'll work on an example and look into that issue.

**Comment by suyash** [comment]
daemon is tracked in #7, example was added in #44, closing this
