### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by sagikazarmark** [performancecopilot/speed#59]
As the title says: Is this package still maintained? Do you accept PRs?

I'd like to update the dependencies of this package, particularly `github.com/codahale/hdrhistogram` as it's been moved to a new place.

Would you accept a PR like that? Or am I better off forking the library?

Thanks!

**Comment by natoscott** [comment]
@sagikazarmark please go ahead and open a PR - thanks!

**Comment by sagikazarmark** [comment]
Thanks @natoscott !

Please see #60 and #61
